model_list:
- model_name: text-embedding-3-small
  litellm_params:
    model: azure/text-embedding-3-small
    api_base: os.environ/AZURE_API_BASE
    api_key: os.environ/AZURE_API_KEY
    api_version: os.environ/AZURE_API_VERSION
- model_name: gpt-4o-mini
  litellm_params:
    model: azure/gpt-4o-mini
    api_base: os.environ/AZURE_API_BASE
    api_key: os.environ/AZURE_API_KEY
    api_version: os.environ/AZURE_API_VERSION
- model_name: gpt-4o
  litellm_params:
    model: azure/gpt-4o
    api_base: os.environ/AZURE_API_BASE
    api_key: os.environ/AZURE_API_KEY
    api_version: os.environ/AZURE_API_VERSION
- model_name: "gemini-2.0-flash-exp"
  litellm_params:
    model: gemini/gemini-2.0-flash-exp
    api_key: os.environ/GEMINI_API_KEY
- model_name: deepseek-chat
  litellm_params:
    model: deepseek/deepseek-chat
    api_key: os.environ/DEEPSEEK_API_KEY

litellm_settings:
  # global_disable_no_log_param: true
  # turn_off_message_logging: true
  timeout: 30
  set_verbose: false
  cache: true
  cache_params:
    type: redis
    host: "redis"
    port: 6379
    password: "password"
    namespace: "litellm.caching.caching"
  disable_master_key_return: boolean
  content_policy_fallbacks: [{"gpt-4o": ["deepseek-chat"]}, {"gpt-4o-mini": ["deepseek-chat"]}]



  # num_retries: 5
  # request_timeout: 10 # raise Timeout error if call takes longer than 10s. Sets litellm.request_timeout
  # fallbacks: [{"gpt-4o-mini": ["deepseek-chat"]}, {"gpt-4o": ["deepseek-chat"]}]
  # allowed_fails: 5
  # cooldown_time: 60 # how long to cooldown model if fails/min > allowed_fails

  # default_fallbacks: ["deepseek-chat"]
